/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Supabase configuration with environment variable fallbacks
// Safe environment variable access for Vite
const getEnvVar = (key: string, fallback: string): string => {
  if (typeof window !== 'undefined') {
    // Browser environment - check window object
    return (window as any)[key] || fallback;
  }
  if (typeof import.meta !== 'undefined' && (import.meta as any).env) {
    // Vite environment
    return (import.meta as any).env[key] || fallback;
  }
  // Fallback
  return fallback;
};

export const supabaseUrl = getEnvVar('VITE_SUPABASE_URL', "https://ecjuilkiworwehktwnxe.supabase.co");
export const publicAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY', "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjanVpbGtpd29yd2Voa3R3bnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzQwMDgsImV4cCI6MjA3MjIxMDAwOH0.F_UlSqn6QXXgQL-IYyhTMURY0XDNxGEK6Ft01sN6Z0o");

// Backwards compatibility
export const projectId = supabaseUrl.split('.')[0].split('//')[1];